core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

main/urls.py
from django.urls import path
from main import views



urlpatterns = [
    path('', views.index, name="index" ),
    path('upload', views.upload, name="upload"),
    path('book/<int:id>', views.book_detail, name="book_detail"),
    path('books/ajax/get-departments', views.get_departments, name="get-departments")
]

main/models.py
from django.db import models

# Create your models here.

COURSE_CHOICES = (
    ('BE', 'BE'),
    ('MCA', 'MCA'),
    ('MBA', 'MBA'),
    ('MTech', 'MTech')
)

class Book(models.Model):
    course = models.CharField(max_length=1000, choices=COURSE_CHOICES)
    title = models.CharField(max_length=5000, null=True, blank=True)
    author = models.CharField(max_length=1000, null=True, blank=True)
    edition = models.CharField(max_length=1000, null=True, blank=True)
    year = models.IntegerField(null=True, blank=True)
    publisher = models.CharField(max_length=2000, null=True, blank=True)
    department = models.CharField(max_length=1000, null=True, blank=True)
    count = models.IntegerField()

    def __str__(self) -> str:
        return self.title

main/views.py
from django.http import JsonResponse
from django.shortcuts import render
import openpyxl
from django.db.models import Sum, Q
from main.models import Book, COURSE_CHOICES
from django.views.decorators.csrf import csrf_exempt
# Create your views here.


def index(request):
    context = {
        "be_book_count":Book.objects.filter(course="BE").aggregate(Sum('count')),
        "mba_book_count":Book.objects.filter(course="MBA").aggregate(Sum('count')),
        "mca_book_count":Book.objects.filter(course="MCA").aggregate(Sum('count')),
        "mtech_book_count":Book.objects.filter(course="MTech").aggregate(Sum('count')),
        "total_books_count":Book.objects.aggregate(Sum('count')),
        "courses":COURSE_CHOICES
    }
    if request.method == "POST":
        query = request.POST.get("search")
        results = Book.objects.filter(Q(title__icontains=query) | Q(author__icontains=query) | Q(department__icontains=query) ).order_by("title")
        context["results"] = results
        context["search_result"] = True
    return render(request, "main/index.html", context)


def book_detail(request, id):
    context = {
        "book":Book.objects.get(id=id)
    }
    return render(request, "main/book_detail.html", context)


@csrf_exempt
def get_departments(request):
    departments = Book.objects.filter(course = 'BE').distinct().values_list("department", flat=True)
    return JsonResponse({'departments':list(departments)})

def upload(request):
    context = dict()
    if request.method == "POST":
        file = request.FILES.get("excel")
        wb = openpyxl.load_workbook(file, read_only=True)
        sheet = wb.active
        fields = [field.name for field in Book._meta.fields]
        fields.remove("id")
        for row in sheet.iter_rows(min_row=2):
            row_value = [x.value for x in row]
            nary = dict(zip(fields, row_value))
            Book.objects.get_or_create(**nary)
        context["uploaded"] = True
    context["row_count"] = Book.objects.count() 
    return render(request, "main/upload.html", context)

main/templates/addon/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">
            <img src="{% static 'logo.svg' %}" alt="" width="30" height="24" class="d-inline-block align-text-top">
            Library @ <b>CIT</b>
          </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'upload' %}">Upload Data</a>
          </li>

        </ul>
      </div>
    </div>
  </nav>

main/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Library | Cambridge Institute of Technology </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
  </head>
  <body>
      {% include 'addon/navbar.html' %}
    {% block content %}
    
    {% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>

main/templates/main/book_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="card">
        <div class="card-body">
          <h5 class="card-title">{{ book.title }}</h5>
          {% if book.edition %}
          Edition: <small>{{ book.edition }}</small>
          {% endif %} 
          <p class="card-text">author: {{ book.author }}</p>
        </div>
        <ul class="list-group list-group-flush">
          {% if book.department %}<li class="list-group-item"><b>Department:</b> {{ book.department }}</li>{% endif %} 
          <li class="list-group-item"><b>Publisher:</b> {{ book.publisher }}</li>
          <li class="list-group-item"><b>Year:</b> {{ book.year }}</li>
          <li class="list-group-item"><b>No. of copies in Library: </b>{{ book.count }}</li>
        </ul>
      </div>
</div>
{% endblock content %}

main/templates/main/index.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <table class="table">
        <tbody>
            <tr>
                <th scope="row">Total Books in Library</th>
                <th scope="col">{{ total_books_count.count__sum }}</th>
            </tr>

            <tr>
                <th scope="row">Total B.E Books in Library</th>
                <td>{{ be_book_count.count__sum }}</td>
            </tr>
            <tr>
                <th scope="row">Total MBA Books in Library</th>
                <td>{{ mba_book_count.count__sum }}</td>
            </tr>
            <tr>
                <th scope="row">Total MCA Books in Library</th>
                <td>{{ mca_book_count.count__sum }}</td>
            </tr>
            <tr>
                <th scope="row">Total Tech Books in Library</th>
                <td>{{ mtech_book_count.count__sum }}</td>
            </tr>
        </tbody>
    </table>
    <!-- <div class="card">
        <div class="card-body">
            <div class="mb-3">
                <label for="id_course" class="form-label">Select Course</label>
                <select class="form-control" name="course" id="id_course">
                    <option>--select--</option>
                    {% for course in courses %}
                    <option value="{{ course | last }}">{{ course |last }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="mb-3" id="department_select" style="display: none;">
              <label for="id_department" class="form-label">Select Department</label>
              <select class="form-control" name="department" id="id_department">
                <option>New Delhi</option>
                <option>Istanbul</option>
                <option>Jakarta</option>
              </select>
            </div>
        </div>
    </div> -->
    <form method="post">
        {% csrf_token %}
        <div class="input-group mb-3">
            <input type="search" name="search" class="form-control" placeholder="Search Books, Author.....">
            <span class="input-group-text" id="basic-addon2"><button type="submit" class="border-0"><i
                        class="bi bi-search"></i></button></span>
        </div>
    </form>
    {% if search_result %}
    <p>Showing {{ results | length }} books</p>
    <div class="list-group my-3">
        {% for result in results %}
        <a href="{% url 'book_detail' id=result.id %}" class="list-group-item list-group-item-action">{{ result.title }}
            {% firstof result.edition %}</a>
        {% endfor %}
    </div>
    {% endif %}

</div>
<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    document.getElementById("id_course").addEventListener("change", function (e) {

        course_name = this.value;
        if (course_name === "BE") {
            $("#department_select").
            get_departments();
        }

    })
    function get_departments() {
        $.get(
            "{% url 'get-departments' %}",
            function (data, status) {
                var courses = data["departments"];
                $("#id_course").empty();
                $("#id_course").prepend("<option>--select--</option>");
                courses.forEach(element => {

                    $("#id_course").prepend(
                        `<option value="${element}">${element}</option>`
                    )
                }

            }
        )
    }
</script> -->
{% endblock content %}

main/templates/main/upload.html
{% extends 'base.html' %}
{% block content %}

{% if uploaded %}
<div class="container">
    <div class="alert alert-success" role="alert">
        <strong>Data Uploaded Successfully. Row count: {{ row_count }}</strong>
    </div>
    
</div>
{% endif %}
<div class="container mt-5">
    <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        <div class="mb-3">
          <label class="custom-file">
            <input type="file" name="excel" class="form-control" aria-describedby="fileHelpId">
            <span class="custom-file-control"></span>
          </label>
          <small id="fileHelpId" class="form-text text-muted">Upload Excel Sheet</small>
        </div>
        <button type="submit" class="btn btn-dark">Upload</button>
    </form>
</div>


{% endblock content %}